version: '3'

services:
  php:
    build:
      context: .
    ports:
      - "80:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
    links:
      - mysql
      - postgres
    volumes:
      - ./elastic.ini:/usr/local/etc/php/conf.d/99-elastic.ini
      - ./:/var/www/app
      - ~/.gitconfig:/root/.gitconfig

  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: playground
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: playground
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
